locale: "en-US"

site_theme: "default"

title: "Home"
name: "David Vävinggren"
description: "PhD Student in Machine Learning @ Uppsala University"
url: "https://davidvavinggren.github.io"
baseurl: "" # leave blank for user.github.io root
repository: "davidvavinggren/davidvavinggren.github.io"

author:
  avatar: "david.jpg"
  name: "David Vävinggren"
  bio: "PhD Student in Machine Learning"
  university: "Uppsala University"
  location: "Uppsala, Sweden"
  email: "david.vavinggren@it.uu.se"
  googlescholar: "https://scholar.google.com/citations?user=yAn3qh8AAAAJ&hl=sv"
  orcid: "https://orcid.org/0009-0004-6036-0371"
  github: "davidvavinggren"
  linkedin: "davidvavinggren"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      author_profile: false
      toc: false
      classes: wide

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: Europe/Stockholm

include:
  - _pages
exclude:
  - vendor
  - node_modules
  - Gemfile*

compress_html:
  clippings: all
  ignore:
    envs: development
